services:
    oro_api.get.processor:
        class: Oro\Bundle\ApiBundle\Processor\GetProcessor
        public: false
        arguments:
            - @oro_api.processor_bag
            - get
            - @oro_api.config_provider
            - @oro_api.metadata_provider
        tags:
            - { name: oro.api.action_processor }

    #
    # initialize
    #

    oro_api.get.check_request_type:
        class: Oro\Bundle\ApiBundle\Processor\Shared\JsonApi\CheckRequestType
        tags:
            - { name: oro.api.processor, action: get, group: initialize, priority: 250 }

    oro_api.get.validate_request_type_exists:
        class: Oro\Bundle\ApiBundle\Processor\Shared\ValidateRequestTypeExists
        tags:
            - { name: oro.api.processor, action: get, group: initialize, priority: 210 }

    oro_api.get.validate_class_name_exists:
        class: Oro\Bundle\ApiBundle\Processor\Shared\ValidateClassNameExists
        tags:
            - { name: oro.api.processor, action: get, group: initialize, priority: 210 }

    oro_api.get.normalize_version:
        class: Oro\Bundle\ApiBundle\Processor\Shared\NormalizeVersion
        tags:
            - { name: oro.api.processor, action: get, group: initialize, priority: 200 }

    oro_api.get.initialize_criteria:
        class: Oro\Bundle\ApiBundle\Processor\Shared\InitializeCriteria
        arguments:
            - @oro_entity.orm.entity_class_resolver
        tags:
            - { name: oro.api.processor, action: get, group: initialize, priority: 200 }

    oro_api.get.normalize_include_header:
        class: Oro\Bundle\ApiBundle\Processor\Shared\NormalizeIncludeHeader
        tags:
            - { name: oro.api.processor, action: get, group: initialize, priority: 50 }

    oro_api.get.json_api.normalize_include_parameter:
        class: Oro\Bundle\ApiBundle\Processor\Shared\JsonApi\NormalizeIncludeParameter
        arguments:
            - @oro_api.value_normalizer
        tags:
            - { name: oro.api.processor, action: get, group: initialize, requestType: json_api, priority: 50 }

    oro_api.get.json_api.normalize_fields_parameter:
        class: Oro\Bundle\ApiBundle\Processor\Shared\JsonApi\NormalizeFieldsParameter
        arguments:
            - @oro_api.value_normalizer
        tags:
            - { name: oro.api.processor, action: get, group: initialize, requestType: json_api, priority: 50 }

    oro_api.get.normalize_entity_class:
        class: Oro\Bundle\ApiBundle\Processor\Shared\NormalizeEntityClass
        arguments:
            - @oro_api.value_normalizer
        tags:
            - { name: oro.api.processor, action: get, group: initialize, priority: 20 }

    oro_api.get.set_default_max_related_entities:
        class: Oro\Bundle\ApiBundle\Processor\Shared\SetDefaultMaxRelatedEntities
        tags:
            - { name: oro.api.processor, action: get, group: initialize, priority: -10 }

    oro_api.get.json_api.set_include_filter:
        class: Oro\Bundle\ApiBundle\Processor\Shared\JsonApi\SetIncludeFilter
        arguments:
            - @oro_api.doctrine_helper
        tags:
            - { name: oro.api.processor, action: get, group: initialize, requestType: json_api, priority: -10 }

    oro_api.get.json_api.set_fields_filter:
        class: Oro\Bundle\ApiBundle\Processor\Shared\JsonApi\SetFieldsFilter
        arguments:
            - @oro_api.doctrine_helper
            - @oro_api.json_api.entity_class_transformer
        tags:
            - { name: oro.api.processor, action: get, group: initialize, requestType: json_api, priority: -10 }

    #
    # security_check
    #

    oro_api.get.entity_type_security_check:
        class: Oro\Bundle\ApiBundle\Processor\Shared\EntityTypeSecurityCheck
        arguments:
            - @security.authorization_checker
            - @oro_api.doctrine_helper
            - VIEW
        tags:
            - { name: oro.api.processor, action: get, group: security_check, priority: 10 }

    #
    # normalize_input
    #

    oro_api.get.validate_entity_id_exists:
        class: Oro\Bundle\ApiBundle\Processor\Shared\ValidateEntityIdExists
        tags:
            - { name: oro.api.processor, action: get, group: normalize_input, priority: -100 }

    oro_api.get.rest.normalize_entity_id:
        class: Oro\Bundle\ApiBundle\Processor\Shared\NormalizeEntityId
        arguments:
            - @oro_api.rest.entity_id_transformer
        tags:
            - { name: oro.api.processor, action: get, group: normalize_input, requestType: rest, priority: -110 }

    #
    # build_query
    #

    oro_api.get.complete_criteria:
        class: Oro\Bundle\ApiBundle\Processor\Shared\CompleteCriteria
        arguments:
            - @oro_api.doctrine_helper
        tags:
            - { name: oro.api.processor, action: get, group: build_query, priority: -50 }

    oro_api.get.protect_query_by_acl:
        class: Oro\Bundle\ApiBundle\Processor\Shared\ProtectQueryByAcl
        arguments:
            - @oro_security.acl_helper
            - VIEW
        tags:
            - { name: oro.api.processor, action: get, group: build_query, priority: -90 }

    oro_api.get.build_query:
        class: Oro\Bundle\ApiBundle\Processor\Get\BuildQuery
        arguments:
            - @oro_api.doctrine_helper
        tags:
            - { name: oro.api.processor, action: get, group: build_query, priority: -100 }

    #
    # load_data
    #

    oro_api.get.load_data_by_entity_serializer:
        class: Oro\Bundle\ApiBundle\Processor\Get\LoadDataByEntitySerializer
        arguments:
            - @oro_api.entity_serializer
        tags:
            - { name: oro.api.processor, action: get, group: load_data, priority: -10 }

    oro_api.get.load_data_by_orm_query:
        class: Oro\Bundle\ApiBundle\Processor\Get\LoadDataByOrmQuery
        tags:
            - { name: oro.api.processor, action: get, group: load_data, priority: -20 }

    #
    # normalize_data
    #

    oro_api.get.initialize_entity_proxy:
        class: Oro\Bundle\ApiBundle\Processor\Get\InitializeEntityProxy
        tags:
            - { name: oro.api.processor, action: get, group: normalize_data, priority: 10 }

    oro_api.get.normalize_data:
        class: Oro\Bundle\ApiBundle\Processor\Get\NormalizeData
        arguments:
            - @oro_api.object_normalizer
        tags:
            - { name: oro.api.processor, action: get, group: normalize_data, priority: -10 }

    #
    # finalize
    #

    oro_api.get.validate_result:
        class: Oro\Bundle\ApiBundle\Processor\Get\ValidateResult
        tags:
            - { name: oro.api.processor, action: get, group: finalize, priority: -250 }

    #
    # normalize_result
    #

    oro_api.get.rest.set_http_response_status_code:
        class: Oro\Bundle\ApiBundle\Processor\Shared\SetHttpResponseStatusCode
        tags:
            - { name: oro.api.processor, action: get, group: normalize_result, requestType: rest, priority: -10 }

    oro_api.get.normalize_errors:
        class: Oro\Bundle\ApiBundle\Processor\Shared\NormalizeErrors
        arguments:
            - @translator
        tags:
            - { name: oro.api.processor, action: get, group: normalize_result, priority: -10 }

    oro_api.get.json_api.build_json_api_document:
        class: Oro\Bundle\ApiBundle\Processor\Get\JsonApi\BuildJsonApiDocument
        arguments:
            - @oro_api.json_api.document_builder_factory
        tags:
            - { name: oro.api.processor, action: get, group: normalize_result, requestType: json_api, priority: -20 }

    oro_api.get.process_errors:
        class: Oro\Bundle\ApiBundle\Processor\Shared\ProcessErrors
        tags:
            - { name: oro.api.processor, action: get, group: normalize_result, priority: -100 }

    oro_api.get.json_api.validate_result_schema:
        class: Oro\Bundle\ApiBundle\Processor\Shared\JsonApi\ValidateResultSchema
        tags:
            - { name: oro.api.processor, action: get, group: normalize_result, requestType: json_api, priority: -200 }

    oro_api.get.json_api.set_response_content_type:
        class: Oro\Bundle\ApiBundle\Processor\Shared\JsonApi\SetResponseContentType
        tags:
            - { name: oro.api.processor, action: get, group: normalize_result, requestType: json_api, priority: -250 }
