services:
    oro_api.get_list.processor:
        class: Oro\Bundle\ApiBundle\Processor\GetListProcessor
        public: false
        arguments:
            - @oro_api.processor_bag
            - get_list
            - @oro_api.config_provider
            - @oro_api.metadata_provider
        tags:
            - { name: oro.api.action_processor }

    #
    # initialize
    #

    oro_api.get_list.check_request_type:
        class: Oro\Bundle\ApiBundle\Processor\Shared\JsonApi\CheckRequestType
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, priority: 250 }

    oro_api.get_list.validate_request_type_exists:
        class: Oro\Bundle\ApiBundle\Processor\Shared\ValidateRequestTypeExists
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, priority: 210 }

    oro_api.get_list.validate_class_name_exists:
        class: Oro\Bundle\ApiBundle\Processor\Shared\ValidateClassNameExists
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, priority: 210 }

    oro_api.get_list.normalize_version:
        class: Oro\Bundle\ApiBundle\Processor\Shared\NormalizeVersion
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, priority: 200 }

    oro_api.get_list.initialize_criteria:
        class: Oro\Bundle\ApiBundle\Processor\Shared\InitializeCriteria
        arguments:
            - @oro_entity.orm.entity_class_resolver
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, priority: 200 }

    oro_api.get_list.normalize_include_header:
        class: Oro\Bundle\ApiBundle\Processor\Shared\NormalizeIncludeHeader
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, priority: 50 }

    oro_api.get_list.json_api.normalize_include_parameter:
        class: Oro\Bundle\ApiBundle\Processor\Shared\JsonApi\NormalizeIncludeParameter
        arguments:
            - @oro_api.value_normalizer
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, requestType: json_api, priority: 50 }

    oro_api.get_list.json_api.normalize_fields_parameter:
        class: Oro\Bundle\ApiBundle\Processor\Shared\JsonApi\NormalizeFieldsParameter
        arguments:
            - @oro_api.value_normalizer
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, requestType: json_api, priority: 50 }

    oro_api.get_list.normalize_entity_class:
        class: Oro\Bundle\ApiBundle\Processor\Shared\NormalizeEntityClass
        arguments:
            - @oro_api.value_normalizer
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, priority: 20 }

    oro_api.get_list.set_default_max_related_entities:
        class: Oro\Bundle\ApiBundle\Processor\Shared\SetDefaultMaxRelatedEntities
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, priority: -10 }

    oro_api.get_list.register_filters:
        class: Oro\Bundle\ApiBundle\Processor\GetList\RegisterFilters
        arguments:
            - @oro_api.filter_factory
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, priority: -50 }

    oro_api.get_list.json_api.normalize_filter_keys:
        class: Oro\Bundle\ApiBundle\Processor\GetList\JsonApi\NormalizeFilterKeys
        arguments:
            - @oro_api.doctrine_helper
            - @translator
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, requestType: json_api, priority: -50 }

    oro_api.get_list.rest.set_default_sorting:
        class: Oro\Bundle\ApiBundle\Processor\GetList\Rest\SetDefaultSorting
        arguments:
            - @oro_api.doctrine_helper
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, requestType: rest, priority: -100 }

    oro_api.get_list.rest.set_default_paging:
        class: Oro\Bundle\ApiBundle\Processor\GetList\Rest\SetDefaultPaging
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, requestType: rest, priority: -100 }

    oro_api.get_list.json_api.set_default_sorting:
        class: Oro\Bundle\ApiBundle\Processor\GetList\JsonApi\SetDefaultSorting
        arguments:
            - @oro_api.doctrine_helper
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, requestType: json_api, priority: -105 }

    oro_api.get_list.json_api.set_default_paging:
        class: Oro\Bundle\ApiBundle\Processor\GetList\JsonApi\SetDefaultPaging
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, requestType: json_api, priority: -105 }

    oro_api.get_list.json_api.set_include_filter:
        class: Oro\Bundle\ApiBundle\Processor\Shared\JsonApi\SetIncludeFilter
        arguments:
            - @oro_api.doctrine_helper
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, requestType: json_api, priority: -110 }

    oro_api.get_list.json_api.set_fields_filter:
        class: Oro\Bundle\ApiBundle\Processor\Shared\JsonApi\SetFieldsFilter
        arguments:
            - @oro_api.doctrine_helper
            - @oro_api.json_api.entity_class_transformer
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, requestType: json_api, priority: -110 }

    #
    # security_check
    #

    oro_api.get_list.entity_type_security_check:
        class: Oro\Bundle\ApiBundle\Processor\Shared\EntityTypeSecurityCheck
        arguments:
            - @security.authorization_checker
            - @oro_api.doctrine_helper
            - VIEW
        tags:
            - { name: oro.api.processor, action: get_list, group: security_check, priority: 10 }

    #
    # normalize_input
    #

    oro_api.get_list.json_api.correct_sort_value:
        class: Oro\Bundle\ApiBundle\Processor\GetList\JsonApi\CorrectSortValue
        arguments:
            - @oro_api.doctrine_helper
        tags:
            - { name: oro.api.processor, action: get_list, group: normalize_input, requestType: json_api, priority: 10 }

    oro_api.get_list.normalize_filter_values:
        class: Oro\Bundle\ApiBundle\Processor\GetList\NormalizeFilterValues
        arguments:
            - @oro_api.value_normalizer
        tags:
            - { name: oro.api.processor, action: get_list, group: normalize_input, priority: -10 }

    oro_api.get_list.validate_sorting:
        class: Oro\Bundle\ApiBundle\Processor\GetList\ValidateSorting
        tags:
            - { name: oro.api.processor, action: get_list, group: normalize_input, priority: -100 }

    #
    # build_query
    #

    oro_api.get_list.build_criteria:
        class: Oro\Bundle\ApiBundle\Processor\GetList\BuildCriteria
        tags:
            - { name: oro.api.processor, action: get_list, group: build_query, priority: 50 }

    oro_api.get_list.complete_criteria:
        class: Oro\Bundle\ApiBundle\Processor\Shared\CompleteCriteria
        arguments:
            - @oro_api.doctrine_helper
        tags:
            - { name: oro.api.processor, action: get_list, group: build_query, priority: -50 }

    oro_api.get_list.optimize_criteria:
        class: Oro\Bundle\ApiBundle\Processor\GetList\OptimizeCriteria
        tags:
            - { name: oro.api.processor, action: get_list, group: build_query, priority: -60 }

    oro_api.get_list.normalize_paging:
        class: Oro\Bundle\ApiBundle\Processor\GetList\NormalizePaging
        tags:
            - { name: oro.api.processor, action: get_list, group: build_query, priority: -60 }

    oro_api.get_list.protect_query_by_acl:
        class: Oro\Bundle\ApiBundle\Processor\Shared\ProtectQueryByAcl
        arguments:
            - @oro_security.acl_helper
            - VIEW
        tags:
            - { name: oro.api.processor, action: get_list, group: build_query, priority: -90 }

    oro_api.get_list.build_query:
        class: Oro\Bundle\ApiBundle\Processor\GetList\BuildQuery
        arguments:
            - @oro_api.doctrine_helper
        tags:
            - { name: oro.api.processor, action: get_list, group: build_query, priority: -100 }

    #
    # load_data
    #

    oro_api.get_list.load_data_by_entity_serializer:
        class: Oro\Bundle\ApiBundle\Processor\GetList\LoadDataByEntitySerializer
        arguments:
            - @oro_api.entity_serializer
        tags:
            - { name: oro.api.processor, action: get_list, group: load_data, priority: -10 }

    oro_api.get_list.load_data_by_orm_query:
        class: Oro\Bundle\ApiBundle\Processor\GetList\LoadDataByOrmQuery
        tags:
            - { name: oro.api.processor, action: get_list, group: load_data, priority: -20 }

    oro_api.get_list.load_data_by_sql_query:
        class: Oro\Bundle\ApiBundle\Processor\GetList\LoadDataBySqlQuery
        tags:
            - { name: oro.api.processor, action: get_list, group: load_data, priority: -30 }

    oro_api.get_list.load_data_by_search_query:
        class: Oro\Bundle\ApiBundle\Processor\GetList\LoadDataBySearchQuery
        arguments:
            - @oro_search.index
        tags:
            - { name: oro.api.processor, action: get_list, group: load_data, priority: -40 }

    #
    # normalize_data
    #

    oro_api.get_list.initialize_entity_proxy:
        class: Oro\Bundle\ApiBundle\Processor\GetList\InitializeEntityProxy
        tags:
            - { name: oro.api.processor, action: get_list, group: normalize_data, priority: 10 }

    oro_api.get_list.normalize_data:
        class: Oro\Bundle\ApiBundle\Processor\GetList\NormalizeData
        arguments:
            - @oro_api.object_normalizer
        tags:
            - { name: oro.api.processor, action: get_list, group: normalize_data, priority: -10 }

    #
    # finalize
    #

    oro_api.get_list.set_total_count_header:
        class: Oro\Bundle\ApiBundle\Processor\GetList\SetTotalCountHeader
        arguments:
            - @oro_batch.orm.query_builder.count_query_optimizer
        tags:
            - { name: oro.api.processor, action: get_list, group: finalize, priority: -10 }

    oro_api.get_list.validate_result:
        class: Oro\Bundle\ApiBundle\Processor\GetList\ValidateResult
        tags:
            - { name: oro.api.processor, action: get_list, group: finalize, priority: -250 }

    #
    # normalize_result
    #

    oro_api.get_list.rest.set_http_response_status_code:
        class: Oro\Bundle\ApiBundle\Processor\Shared\SetHttpResponseStatusCode
        tags:
            - { name: oro.api.processor, action: get_list, group: normalize_result, requestType: rest, priority: -10 }

    oro_api.get_list.normalize_errors:
        class: Oro\Bundle\ApiBundle\Processor\Shared\NormalizeErrors
        arguments:
            - @translator
        tags:
            - { name: oro.api.processor, action: get_list, group: normalize_result, priority: -10 }

    oro_api.get_list.json_api.build_json_api_document:
        class: Oro\Bundle\ApiBundle\Processor\GetList\JsonApi\BuildJsonApiDocument
        arguments:
            - @oro_api.json_api.document_builder_factory
        tags:
            - { name: oro.api.processor, action: get_list, group: normalize_result, requestType: json_api, priority: -20 }

    oro_api.get_list.rest.process_errors:
        class: Oro\Bundle\ApiBundle\Processor\Shared\ProcessErrors
        tags:
            - { name: oro.api.processor, action: get_list, group: normalize_result, requestType: rest, priority: -100 }

    oro_api.get_list.json_api.validate_result_schema:
        class: Oro\Bundle\ApiBundle\Processor\Shared\JsonApi\ValidateResultSchema
        tags:
            - { name: oro.api.processor, action: get_list, group: normalize_result, requestType: json_api, priority: -200 }

    oro_api.get_list.json_api.validate_result:
        class: Oro\Bundle\ApiBundle\Processor\GetList\JsonApi\ValidateResult
        tags:
            - { name: oro.api.processor, action: get_list, group: normalize_result, requestType: json_api, priority: -210 }

    oro_api.get_list.json_api.set_response_content_type:
        class: Oro\Bundle\ApiBundle\Processor\Shared\JsonApi\SetResponseContentType
        tags:
            - { name: oro.api.processor, action: get_list, group: normalize_result, requestType: json_api, priority: -250 }
