parameters:
    oro_workflow.form.event_listener.default_values.class: Oro\Bundle\WorkflowBundle\Form\EventListener\DefaultValuesListener
    oro_workflow.form.event_listener.init_actions.class: Oro\Bundle\WorkflowBundle\Form\EventListener\InitActionsListener
    oro_workflow.form.event_listener.required_attributes.class: Oro\Bundle\WorkflowBundle\Form\EventListener\RequiredAttributesListener

    oro_workflow.form.type.attributes.class: Oro\Bundle\WorkflowBundle\Form\Type\WorkflowAttributesType
    oro_workflow.form.type.transition.class: Oro\Bundle\WorkflowBundle\Form\Type\WorkflowTransitionType
    oro_workflow.form.type.workflow_step_select.class: Oro\Bundle\WorkflowBundle\Form\Type\WorkflowStepSelectType
    oro_workflow.form.type.workflow_select.class: Oro\Bundle\WorkflowBundle\Form\Type\WorkflowSelectType
    oro_workflow.form.type.applicable_entities.class: Oro\Bundle\WorkflowBundle\Form\Type\ApplicableEntitiesType

    oro_workflow.form.type.workflow_definition.class: Oro\Bundle\WorkflowBundle\Form\Type\WorkflowDefinitionType

services:
    oro_workflow.form.event_listener.default_values:
        class: %oro_workflow.form.event_listener.default_values.class%
        arguments: [@oro_workflow.context_accessor]

    oro_workflow.form.event_listener.init_actions:
        class: %oro_workflow.form.event_listener.init_actions.class%

    oro_workflow.form.event_listener.required_attributes:
        class: %oro_workflow.form.event_listener.required_attributes.class%

    oro_workflow.form.type.attributes:
        class: %oro_workflow.form.type.attributes.class%
        arguments:
            - @oro_workflow.registry
            - @oro_workflow.attribute_guesser
            - @oro_workflow.form.event_listener.default_values
            - @oro_workflow.form.event_listener.init_actions
            - @oro_workflow.form.event_listener.required_attributes
            - @oro_workflow.context_accessor
            - @event_dispatcher
        tags:
            - { name: form.type, alias: oro_workflow_attributes }

    oro_workflow.form.type.transition:
        class: %oro_workflow.form.type.transition.class%
        tags:
            - { name: form.type, alias: oro_workflow_transition }

    oro_workflow.form.type.workflow_step_select:
        class: %oro_workflow.form.type.workflow_step_select.class%
        arguments:
            - @oro_workflow.manager
        tags:
            - { name: form.type, alias: oro_workflow_step_select }

    oro_workflow.form.type.workflow_select:
        class: %oro_workflow.form.type.workflow_select.class%
        arguments:
            - @doctrine
        tags:
            - { name: form.type, alias: oro_workflow_select }

    oro_workflow.form.type.workflow_definition:
        class: %oro_workflow.form.type.workflow_definition.class%
        tags:
            - { name: form.type, alias: oro_workflow_definition }

    oro_workflow.form.type.applicable_entities:
        class: %oro_workflow.form.type.applicable_entities.class%
        arguments:
            - @oro_entity_config.config_manager
            - @oro_workflow.entity_connector
        tags:
            - { name: form.type, alias: oro_workflow_applicable_entities }

    oro_workflow.form.workflow_definition:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["oro_workflow_definition_form", "oro_workflow_definition", null]
