parameters:
    oro_datagrid.extension.toolbar.class:          Oro\Bundle\DataGridBundle\Extension\Toolbar\ToolbarExtension
    oro_datagrid.extension.formatter.class:        Oro\Bundle\DataGridBundle\Extension\Formatter\FormatterExtension
    oro_datagrid.extension.orm_pager.class:        Oro\Bundle\DataGridBundle\Extension\Pager\OrmPagerExtension
    oro_datagrid.extension.pager.orm.pager.class:  Oro\Bundle\DataGridBundle\Extension\Pager\Orm\Pager
    oro_datagrid.extension.orm_sorter.class:       Oro\Bundle\DataGridBundle\Extension\Sorter\OrmSorterExtension
    oro_datagrid.extension.inline_editing.class:   Oro\Bundle\DataGridBundle\Extension\InlineEditing\InlineEditingExtension
    oro_datagrid.extension.action.class:           Oro\Bundle\DataGridBundle\Extension\Action\ActionExtension
    oro_datagrid.extension.mass_action.class:      Oro\Bundle\DataGridBundle\Extension\MassAction\MassActionExtension
    oro_datagrid.extension.views.class:            Oro\Bundle\DataGridBundle\Extension\GridViews\GridViewsExtension
    oro_datagrid.extension.export.class:           Oro\Bundle\DataGridBundle\Extension\Export\ExportExtension
    oro_datagrid.extension.gridparams.class:       Oro\Bundle\DataGridBundle\Extension\GridParams\GridParamsExtension
    oro_datagrid.extension.totals.class:           Oro\Bundle\DataGridBundle\Extension\Totals\OrmTotalsExtension
    oro_datagrid.extension.columns.class:          Oro\Bundle\DataGridBundle\Extension\Columns\ColumnsExtension
    oro_datagrid.extension.mode.class:             Oro\Bundle\DataGridBundle\Extension\Mode\ModeExtension
    oro_datagrid.extension.postgresql_grid_modifier.class: Oro\Bundle\DataGridBundle\Extension\Sorter\PostgresqlGridModifier

services:
    oro_datagrid.extension.formatter:
        class: %oro_datagrid.extension.formatter.class%
        arguments:
            - @translator
        tags:
            - { name: oro_datagrid.extension }
        lazy: true

    oro_datagrid.extension.orm_pager:
        class: %oro_datagrid.extension.orm_pager.class%
        arguments:
            - @oro_datagrid.extension.pager.orm.pager
        tags:
            - { name: oro_datagrid.extension }

    oro_datagrid.extension.pager.orm.pager:
        arguments:
            - @oro_security.acl_helper
            - @oro_batch.orm.query_builder.count_query_optimizer
        class: %oro_datagrid.extension.pager.orm.pager.class%

    oro_datagrid.extension.orm_sorter:
        class: %oro_datagrid.extension.orm_sorter.class%
        tags:
            - { name: oro_datagrid.extension }

    oro_datagrid.extension.inline_editing:
        class: %oro_datagrid.extension.inline_editing.class%
        arguments:
            - @oro_datagrid.datagrid.inline_edit_column_options_guesser
            - @oro_security.security_facade
            - @oro_entity.entity_class_name_helper
        tags:
            - { name: oro_datagrid.extension }

    oro_datagrid.extension.action:
        class: %oro_datagrid.extension.action.class%
        arguments:
            - @service_container
            - @oro_security.security_facade
            - @translator
        tags:
            - { name: oro_datagrid.extension }

    oro_datagrid.extension.mass_delete_action:
        class: Oro\Bundle\DataGridBundle\Extension\MassAction\DeleteMassActionExtension
        arguments:
            - @oro_entity.doctrine_helper
            - @oro_datagrid.grid_configuration.helper
        tags:
            - { name: oro_datagrid.extension }

    oro_datagrid.extension.mass_action:
        class: %oro_datagrid.extension.mass_action.class%
        arguments:
            - @service_container
            - @oro_security.security_facade
            - @translator
        tags:
            - { name: oro_datagrid.extension }

    oro_datagrid.extension.toolbar:
        class: %oro_datagrid.extension.toolbar.class%
        arguments:
            - @oro_config.user
        tags:
            - { name: oro_datagrid.extension }

    oro_datagrid.extension.views:
        class: %oro_datagrid.extension.views.class%
        arguments:
            - @event_dispatcher
            - @oro_security.security_facade
            - @translator
            - @doctrine
            - @oro_security.acl_helper
        tags:
            - { name: oro_datagrid.extension }

    oro_datagrid.extension.export:
        class: %oro_datagrid.extension.export.class%
        arguments:
            - @translator
        tags:
            - { name: oro_datagrid.extension }

    oro_datagrid.extension.gridparams:
        class: %oro_datagrid.extension.gridparams.class%
        tags:
            - { name: oro_datagrid.extension }

    oro_datagrid.extension.totals:
        class: %oro_datagrid.extension.totals.class%
        arguments:
            - @translator
            - @oro_locale.formatter.number
            - @oro_locale.formatter.date_time
            - @oro_security.acl_helper
        tags:
            - { name: oro_datagrid.extension }

    oro_datagrid.extension.columns:
        class: %oro_datagrid.extension.columns.class%
        arguments:
            - @doctrine
            - @oro_security.security_facade
            - @oro_security.acl_helper
            - @oro_datagrid.columns.helper
        tags:
            - { name: oro_datagrid.extension }

    oro_datagrid.extension.mode:
        class: %oro_datagrid.extension.mode.class%
        tags:
            - { name: oro_datagrid.extension }

    oro_datagrid.extension.postgresql_grid_modifier:
        class: %oro_datagrid.extension.postgresql_grid_modifier.class%
        arguments:
            - %database_driver%
            - @oro_entity.orm.entity_class_resolver
        tags:
            - { name: oro_datagrid.extension }
