parameters:
    oro_datagrid.extension.mass_action.handler.delete.class:  Oro\Bundle\DataGridBundle\Extension\MassAction\DeleteMassActionHandler
    oro_datagrid.mass_action.parameters_parser.class:         Oro\Bundle\DataGridBundle\Extension\MassAction\MassActionParametersParser
    oro_datagrid.mass_action.dispatcher.class:                Oro\Bundle\DataGridBundle\Extension\MassAction\MassActionDispatcher

    oro_datagrid.extension.mass_action.type.ajax.class:       Oro\Bundle\DataGridBundle\Extension\MassAction\Actions\Ajax\AjaxMassAction
    oro_datagrid.extension.mass_action.type.delete.class:     Oro\Bundle\DataGridBundle\Extension\MassAction\Actions\Ajax\DeleteMassAction

    oro_datagrid.extension.mass_action.type.redirect.class:   Oro\Bundle\DataGridBundle\Extension\MassAction\Actions\Redirect\RedirectMassAction
    oro_datagrid.extension.mass_action.type.widget.class:     Oro\Bundle\DataGridBundle\Extension\MassAction\Actions\Widget\WidgetMassAction
    oro_datagrid.extension.mass_action.type.window.class:     Oro\Bundle\DataGridBundle\Extension\MassAction\Actions\Widget\WindowMassAction
    oro_datagrid.extension.mass_action.type.frontend.class:     Oro\Bundle\DataGridBundle\Extension\MassAction\Actions\FrontendMassAction
services:
    oro_datagrid.extension.mass_action.handler.delete:
        class: %oro_datagrid.extension.mass_action.handler.delete.class%
        arguments:
            - '@doctrine'
            - '@translator'
            - '@oro_security.security_facade'
            - '@oro_datagrid.extension.mass_action.actions.ajax.mass_delete_limiter'
            - '@request_stack'
            - '@oro_platform.optional_listeners.manager'

    oro_datagrid.mass_action.parameters_parser:
        class: %oro_datagrid.mass_action.parameters_parser.class%

    oro_datagrid.mass_action.dispatcher:
        class: %oro_datagrid.mass_action.dispatcher.class%
        arguments:
            - '@service_container'
            - '@oro_datagrid.datagrid.manager'
            - '@oro_security.acl_helper'

    oro_datagrid.extension.mass_action.type.ajax:
        class: %oro_datagrid.extension.mass_action.type.ajax.class%
        scope: prototype
        tags:
            - { name:  oro_datagrid.extension.mass_action.type, type: ajax }

    oro_datagrid.extension.mass_action.type.delete:
        class: %oro_datagrid.extension.mass_action.type.delete.class%
        scope: prototype
        tags:
            - { name:  oro_datagrid.extension.mass_action.type, type: delete }

    oro_datagrid.extension.mass_action.type.redirect:
        class: %oro_datagrid.extension.mass_action.type.redirect.class%
        scope: prototype
        tags:
            - { name:  oro_datagrid.extension.mass_action.type, type: redirect }

    oro_datagrid.extension.mass_action.type.widget:
        class: %oro_datagrid.extension.mass_action.type.widget.class%
        scope: prototype
        tags:
            - { name:  oro_datagrid.extension.mass_action.type, type: widget }

    oro_datagrid.extension.mass_action.type.window:
        class: %oro_datagrid.extension.mass_action.type.window.class%
        scope: prototype
        tags:
            - { name:  oro_datagrid.extension.mass_action.type, type: window }

    oro_datagrid.extension.mass_action.type.frontend:
        class: %oro_datagrid.extension.mass_action.type.frontend.class%
        scope: prototype
        tags:
            - { name:  oro_datagrid.extension.mass_action.type, type: frontend }

    oro_datagrid.extension.mass_action.actions.ajax.mass_delete_limiter:
        class: Oro\Bundle\DataGridBundle\Extension\MassAction\Actions\Ajax\MassDelete\MassDeleteLimiter
        arguments:
            - '@oro_security.acl_helper'
