parameters:
    oro_importexport.reader.csv.class: Oro\Bundle\ImportExportBundle\Reader\CsvFileReader
    oro_importexport.reader.entity.class: Oro\Bundle\ImportExportBundle\Reader\EntityReader
    oro_importexport.reader.template_fixture.class: Oro\Bundle\ImportExportBundle\Reader\TemplateFixtureReader

services:
    oro_importexport.reader.csv:
        class: %oro_importexport.reader.csv.class%
        arguments:
            - @oro_importexport.context_registry

    oro_importexport.reader.entity:
        class: %oro_importexport.reader.entity.class%
        arguments:
            - @oro_importexport.context_registry
            - @doctrine
            - @oro_security.owner.ownership_metadata_provider
        calls:
            - [setDispatcher, [@event_dispatcher]]
            - [setAclHelper, [@oro_security.acl_helper]]

    oro_importexport.reader.template_fixture:
        class: %oro_importexport.reader.template_fixture.class%
        arguments:
            - @oro_importexport.context_registry
            - @oro_importexport.template_fixture.manager
