definitions:
    sync_email_flag_after_changed:
        label:   Sync Email Flag After Changed
        enabled: true
        order:   50
        entity:  Oro\Bundle\EmailBundle\Entity\EmailUser
        pre_conditions:
            @and:
                - @not_empty: [$origin]
                - @equal: [$origin.active, true]
        actions_configuration:
            - @tree:
                conditions:
                    @equal: [$seen, false]
                actions:
                    - @call_method:
                        object: $.data
                        method: incrementUnsyncedFlagCount
                    - @format_string:
                        attribute: $.arguments
                        string: '--ids=%id%'
                        arguments:
                            id: $id
                    - @create_entity:
                        class: JMS\JobQueueBundle\Entity\Job
                        attribute: $.syncJob
                        flush: true
                        arguments:
                            - 'oro:email:flag-sync'
                            - ['--seen=false', $.arguments]
            - @tree:
                conditions:
                    @equal: [$seen, true]
                actions:
                    - @call_method:
                        object: $.data
                        method: incrementUnsyncedFlagCount
                    - @format_string:
                        attribute: $.arguments
                        string: '--ids=%id%'
                        arguments:
                            id: $id
                    - @create_entity:
                        class: JMS\JobQueueBundle\Entity\Job
                        attribute: $.syncJob
                        flush: true
                        arguments:
                            - 'oro:email:flag-sync'
                            - ['--seen=true', $.arguments]

triggers:
    sync_email_flag_after_changed:
        -
            event: update
            field: seen
