oro_system_configuration:
    groups:
        email_configuration:
            icon:  icon-envelope
            title: oro.email.system_configuration.email_configuration

        email_autocomplete_configuration:
            title: oro.email.system_configuration.email_autocomplete_configuration.label
            priority: 120

        signature_configuration:
            title: oro.email.system_configuration.signature_configuration.label
            priority: 100

        email_threads:
            title: oro.email.system_configuration.email_threads.label
            priority: 90

        reply_configuration:
            title: oro.email.system_configuration.reply_configuration.label
            priority: 80

        attachment_configuration:
            title: oro.email.system_configuration.attachment_configuration.label
            priority: 70

        mailboxes:
            title: oro.email.system_configuration.mailbox_configuration.label
            priority: -10

        user_bar_settings:
            title: oro.user.user_bar_settings.title
            priority: 100

    fields:
        oro_email.minimum_input_length:
            data_type: integer
            type: number
            options:
                label: oro.email.system_configuration.email_autocomplete_configuration.minimum_input_length.label
                precision: 0
                constraints:
                    - NotBlank: ~

        oro_email.signature:
            data_type: string
            type: oro_rich_text
            options:
                label: oro.email.system_configuration.signature_configuration.signature.label
                required: false

        oro_email.append_signature:
            data_type: boolean
            type: choice
            options:
                label: oro.email.system_configuration.signature_configuration.append_signature.label
                choices:
                    1: oro.email.system_configuration.signature_configuration.append_signature.choices.auto.label
                    0: oro.email.system_configuration.signature_configuration.append_signature.choices.manual.label

        oro_email.default_button_reply:
            data_type: integer
            type: choice
            options:
                label: oro.email.system_configuration.reply_configuration.default_button.label
                choices:
                    1: oro.email.reply
                    2: oro.email.reply_all
                required: false

        oro_email.mailbox_grid:
            type: oro_email_mailbox_grid
            ui_only: true
            options:
                label: false
                required: false
                resettable: false
        oro_email.show_recent_emails_in_user_bar:
            data_type: boolean
            type: oro_config_checkbox
            priority: 100
            options:
                label: oro.email.system_configuration.show_recent_emails_in_user_bar.label
                required: true

        oro_email.attachment_sync_enable:
            data_type: boolean
            type: oro_config_checkbox
            priority: 50
            options:
                label: oro.email.system_configuration.attachment_sync.enable.label
                tooltip: oro.email.form.tooltip.attachment_sync.enable
                required: true

        oro_email.attachment_sync_max_size:
            data_type: number
            type: number
            priority: 50
            options:
                label: oro.email.system_configuration.attachment_sync.max_size.label
                tooltip: oro.email.form.tooltip.attachment_sync.max_size
                required: true

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            look_and_feel:
                                children:
                                    user_bar_settings:
                                        children:
                                            - oro_email.show_recent_emails_in_user_bar
                            email_configuration:
                                children:
                                    email_autocomplete_configuration:
                                        children:
                                            - oro_email.minimum_input_length
                                    signature_configuration:
                                        children:
                                            - oro_email.signature
                                            - oro_email.append_signature
                                    reply_configuration:
                                        children:
                                            - oro_email.default_button_reply
                                    attachment_configuration:
                                        children:
                                            - oro_email.attachment_sync_enable
                                            - oro_email.attachment_sync_max_size
                                    mailboxes:
                                        children:
                                            - oro_email.mailbox_grid

    api_tree:
        signature_configuration:
            oro_email.signature: ~
            oro_email.append_signature: ~
        reply_configuration:
            oro_email.default_button_reply: ~
