parameters:
    oro_report.report.entity.class:                    Oro\Bundle\ReportBundle\Entity\Report
    oro_report.datagrid.configuration.provider.class:  Oro\Bundle\ReportBundle\Grid\ReportDatagridConfigurationProvider
    oro_report.listener.navigation_listener.class:     Oro\Bundle\ReportBundle\EventListener\NavigationListener
    oro_report.report_manager.class:                   Oro\Bundle\ReportBundle\Entity\Manager\ReportManager
    oro_report.grid.base_configuration_builder.class:  Oro\Bundle\ReportBundle\Grid\BaseReportConfigurationBuilder
    oro_report.listener.segment_subscriber.class:      Oro\Bundle\ReportBundle\EventListener\SegmentSubscriber

    oro_report.grid.datagrid_configuration_builder.class: Oro\Bundle\ReportBundle\Grid\ReportDatagridConfigurationBuilder
services:
    oro_report.entity_provider:
        alias: oro_entity.entity_provider

    oro_report.datagrid.configuration.provider:
        class: %oro_report.datagrid.configuration.provider.class%
        arguments:
            - @oro_report.grid.datagrid_configuration_builder
            - @doctrine
        tags:
            - { name: oro_datagrid.configuration.provider }

    oro_report.listener.navigation_listener:
        class: %oro_report.listener.navigation_listener.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_entity_config.provider.entity
            - @oro_security.security_facade
            - @oro_security.acl_helper
        tags:
            - { name: kernel.event_listener, event: oro_menu.configure.application_menu, method: onNavigationConfigure }

    oro_report.report_manager:
        class: %oro_report.report_manager.class%
        arguments:
            - @doctrine.orm.entity_manager

    oro_report.grid.base_configuration_builder:
        class: %oro_report.grid.base_configuration_builder.class%
        parent: oro_query_designer.grid.datagrid_configuration_builder
        calls:
            - [setConfigManager, [@oro_entity_config.config_manager]]

    oro_report.grid.datagrid_configuration_builder:
        class: %oro_report.grid.datagrid_configuration_builder.class%
        parent: oro_report.grid.base_configuration_builder

    oro_report.listener.segment_subscriber:
        class: %oro_report.listener.segment_subscriber.class%
        tags:
            - { name: kernel.event_subscriber }

    oro_report.grid.extension.store_sql:
        class: Oro\Bundle\ReportBundle\Grid\StoreSqlExtension
        arguments:
            - @oro_security.security_facade
        tags:
            - { name: oro_datagrid.extension }

    oro_report.event_listener.store_sql:
        class: Oro\Bundle\ReportBundle\EventListener\StoreSqlListener
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.orm_datasource.result.after, method: onResultAfter }
