oro_api:
    entities:
        Oro\Bundle\WorkflowBundle\Entity\ProcessDefinition: ~
        Oro\Bundle\WorkflowBundle\Entity\ProcessJob: ~
        Oro\Bundle\WorkflowBundle\Entity\ProcessTrigger: ~
        Oro\Bundle\WorkflowBundle\Entity\WorkflowDefinition: ~
        Oro\Bundle\WorkflowBundle\Entity\WorkflowEntityAcl: ~
        Oro\Bundle\WorkflowBundle\Entity\WorkflowEntityAclIdentity: ~
        Oro\Bundle\WorkflowBundle\Entity\WorkflowItem: ~
        Oro\Bundle\WorkflowBundle\Entity\WorkflowStep: ~
        Oro\Bundle\WorkflowBundle\Entity\WorkflowTransitionRecord: ~
