oro_api:
    entities:
        Oro\Bundle\EmailBundle\Entity\EmailTemplate: ~
        Oro\Bundle\EmailBundle\Entity\AutoResponseRule: ~
        Oro\Bundle\EmailBundle\Entity\AutoResponseRuleCondition: ~
        Oro\Bundle\EmailBundle\Entity\Email: ~
        Oro\Bundle\EmailBundle\Entity\EmailAttachment: ~
        Oro\Bundle\EmailBundle\Entity\EmailAttachmentContent: ~
        Oro\Bundle\EmailBundle\Entity\EmailBody: ~
        Oro\Bundle\EmailBundle\Entity\EmailFolder: ~
        Oro\Bundle\EmailBundle\Entity\EmailOrigin: ~
        Oro\Bundle\EmailBundle\Entity\EmailRecipient: ~
        Oro\Bundle\EmailBundle\Entity\EmailThread: ~
        Oro\Bundle\EmailBundle\Entity\EmailUser: ~
        Oro\Bundle\EmailBundle\Entity\Mailbox: ~
